[build]
  publish = "public"
  command = "pip install -r requirements.txt && python my_project/src/app.py"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "public/index.html"
  status = 200

