[build]
  publish = "public"
  command = "pip install -r my_project/requirements.txt && python my_project/src/app.py"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "my_project/public/index.html"
  status = 200

