[build]
  publish = "public"
  command = "pip install -r requirements.txt && python src/app.py"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

