[build]
  publish = "public"
  command = "pip install -r requirements.txt && gunicorn src.app:app"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
